name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # checkout sources
    - name: checkout
      uses: actions/checkout@v2
    
    # run make
    - name: run make
      run: make
